{
    "_id" : ObjectId("538617d20c4a30affa150fd1"),
    "userEmail" : "dave.ruyle@gmail.com",
    "brackets" : [ 
        {
            "id" : 0,
            "team1" : "Brazil",
            "team1_key" : "BRA",
            "team2" : "Croatia",
            "team2_key" : "CRO",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Brazil",
            "winnerPickImg" : "images/flags/Brazil.png",
            "winnerPickKey" : "BRA",
            "loserPickKey" : "CRO",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 1,
            "team1" : "Mexico",
            "team1_key" : "MEX",
            "team2" : "Cameroon",
            "team2_key" : "CMR",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Mexico",
            "winnerPickImg" : "images/flags/Mexico.png",
            "winnerPickKey" : "MEX",
            "loserPickKey" : "CMR",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 2,
            "team1" : "Spain",
            "team1_key" : "ESP",
            "team2" : "Netherlands",
            "team2_key" : "NED",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Spain",
            "winnerPickImg" : "images/flags/Spain.png",
            "winnerPickKey" : "ESP",
            "loserPickKey" : "NED",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 3,
            "team1" : "Chile",
            "team1_key" : "CHI",
            "team2" : "Australia",
            "team2_key" : "AUS",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Chile",
            "winnerPickImg" : "images/flags/Chile.png",
            "winnerPickKey" : "CHI",
            "loserPickKey" : "AUS",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 4,
            "team1" : "Colombia",
            "team1_key" : "COL",
            "team2" : "Greece",
            "team2_key" : "GRE",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Colombia",
            "winnerPickImg" : "images/flags/Colombia.png",
            "winnerPickKey" : "COL",
            "loserPickKey" : "GRE",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 5,
            "team1" : "Ivory Coast",
            "team1_key" : "CIV",
            "team2" : "Japan",
            "team2_key" : "JPN",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Ivory Coast",
            "winnerPickImg" : "images/flags/Ivory Coast.png",
            "winnerPickKey" : "CIV",
            "loserPickKey" : "JPN",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 6,
            "team1" : "Uruguay",
            "team1_key" : "URU",
            "team2" : "Costa Rica",
            "team2_key" : "CRC",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Uruguay",
            "winnerPickImg" : "images/flags/Uruguay.png",
            "winnerPickKey" : "URU",
            "loserPickKey" : "CRC",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 7,
            "team1" : "England",
            "team1_key" : "ENG",
            "team2" : "Italy",
            "team2_key" : "ITA",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "England",
            "winnerPickImg" : "images/flags/England.png",
            "winnerPickKey" : "ENG",
            "loserPickKey" : "ITA",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 8,
            "team1" : "Switzerland",
            "team1_key" : "SUI",
            "team2" : "Ecuador",
            "team2_key" : "ECU",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Switzerland",
            "winnerPickImg" : "images/flags/Switzerland.png",
            "winnerPickKey" : "SUI",
            "loserPickKey" : "ECU",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 9,
            "team1" : "France",
            "team1_key" : "FRA",
            "team2" : "Honduras",
            "team2_key" : "HON",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "France",
            "winnerPickImg" : "images/flags/France.png",
            "winnerPickKey" : "FRA",
            "loserPickKey" : "HON",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 10,
            "team1" : "Argentina",
            "team1_key" : "ARG",
            "team2" : "Bosnia",
            "team2_key" : "BIH",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Argentina",
            "winnerPickImg" : "images/flags/Argentina.png",
            "winnerPickKey" : "ARG",
            "loserPickKey" : "BIH",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 11,
            "team1" : "Iran",
            "team1_key" : "IRN",
            "team2" : "Nigeria",
            "team2_key" : "NGA",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Iran",
            "winnerPickImg" : "images/flags/Iran.png",
            "winnerPickKey" : "IRN",
            "loserPickKey" : "NGA",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 12,
            "team1" : "Germany",
            "team1_key" : "GER",
            "team2" : "Portugal",
            "team2_key" : "POR",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Portugal",
            "winnerPickImg" : "images/flags/Portugal.png",
            "winnerPickKey" : "POR",
            "loserPickKey" : "GER",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 13,
            "team1" : "Ghana",
            "team1_key" : "GHA",
            "team2" : "USA",
            "team2_key" : "USA",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Ghana",
            "winnerPickImg" : "images/flags/Ghana.png",
            "winnerPickKey" : "GHA",
            "loserPickKey" : "USA",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 14,
            "team1" : "Belgium",
            "team1_key" : "BEL",
            "team2" : "Algeria",
            "team2_key" : "ALG",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Algeria",
            "winnerPickImg" : "images/flags/Algeria.png",
            "winnerPickKey" : "ALG",
            "loserPickKey" : "BEL",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 15,
            "team1" : "Russia",
            "team1_key" : "RUS",
            "team2" : "South Korea",
            "team2_key" : "KOR",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "South Korea",
            "winnerPickImg" : "images/flags/South Korea.png",
            "winnerPickKey" : "KOR",
            "loserPickKey" : "RUS",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 16,
            "team1" : "Brazil",
            "team1_key" : "BRA",
            "team2" : "Mexico",
            "team2_key" : "MEX",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Brazil",
            "winnerPickImg" : "images/flags/Brazil.png",
            "winnerPickKey" : "BRA",
            "loserPickKey" : "MEX",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 17,
            "team1" : "Cameroon",
            "team1_key" : "CMR",
            "team2" : "Croatia",
            "team2_key" : "CRO",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Cameroon",
            "winnerPickImg" : "images/flags/Cameroon.png",
            "winnerPickKey" : "CMR",
            "loserPickKey" : "CRO",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 18,
            "team1" : "Spain",
            "team1_key" : "ESP",
            "team2" : "Chile",
            "team2_key" : "CHI",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Chile",
            "winnerPickImg" : "images/flags/Chile.png",
            "winnerPickKey" : "CHI",
            "loserPickKey" : "ESP",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 19,
            "team1" : "Australia",
            "team1_key" : "AUS",
            "team2" : "Netherlands",
            "team2_key" : "NED",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Netherlands",
            "winnerPickImg" : "images/flags/Netherlands.png",
            "winnerPickKey" : "NED",
            "loserPickKey" : "AUS",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 20,
            "team1" : "Colombia",
            "team1_key" : "COL",
            "team2" : "Ivory Coast",
            "team2_key" : "CIV",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Colombia",
            "winnerPickImg" : "images/flags/Colombia.png",
            "winnerPickKey" : "COL",
            "loserPickKey" : "CIV",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 21,
            "team1" : "Japan",
            "team1_key" : "JPN",
            "team2" : "Greece",
            "team2_key" : "GRE",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Greece",
            "winnerPickImg" : "images/flags/Greece.png",
            "winnerPickKey" : "GRE",
            "loserPickKey" : "JPN",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 22,
            "team1" : "Uruguay",
            "team1_key" : "URU",
            "team2" : "England",
            "team2_key" : "ENGLAND",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Uruguay",
            "winnerPickImg" : "images/flags/Uruguay.png",
            "winnerPickKey" : "URU",
            "loserPickKey" : "ENGLAND",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 23,
            "team1" : "Italy",
            "team1_key" : "ITA",
            "team2" : "Costa Rica",
            "team2_key" : "CRC",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Italy",
            "winnerPickImg" : "images/flags/Italy.png",
            "winnerPickKey" : "ITA",
            "loserPickKey" : "CRC",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 24,
            "team1" : "Switzerland",
            "team1_key" : "SUI",
            "team2" : "France",
            "team2_key" : "FRA",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Switzerland",
            "winnerPickImg" : "images/flags/Switzerland.png",
            "winnerPickKey" : "SUI",
            "loserPickKey" : "FRA",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 25,
            "team1" : "Honduras",
            "team1_key" : "HON",
            "team2" : "Ecuador",
            "team2_key" : "ECU",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Ecuador",
            "winnerPickImg" : "images/flags/Ecuador.png",
            "winnerPickKey" : "ECU",
            "loserPickKey" : "HON",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 26,
            "team1" : "Argentina",
            "team1_key" : "ARG",
            "team2" : "Iran",
            "team2_key" : "IRN",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Argentina",
            "winnerPickImg" : "images/flags/Argentina.png",
            "winnerPickKey" : "ARG",
            "loserPickKey" : "IRN",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 27,
            "team1" : "Nigeria",
            "team1_key" : "NGA",
            "team2" : "Bosnia",
            "team2_key" : "BIH",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Nigeria",
            "winnerPickImg" : "images/flags/Nigeria.png",
            "winnerPickKey" : "NGA",
            "loserPickKey" : "BIH",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 28,
            "team1" : "Germany",
            "team1_key" : "GER",
            "team2" : "GHANA",
            "team2_key" : "GHA",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "GHANA",
            "winnerPickImg" : "images/flags/GHANA.png",
            "winnerPickKey" : "GHA",
            "loserPickKey" : "GER",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 29,
            "team1" : "USA",
            "team1_key" : "USA",
            "team2" : "Portugal",
            "team2_key" : "POR",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Portugal",
            "winnerPickImg" : "images/flags/Portugal.png",
            "winnerPickKey" : "POR",
            "loserPickKey" : "USA",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 30,
            "team1" : "Belgium",
            "team1_key" : "BEL",
            "team2" : "Russia",
            "team2_key" : "RUS",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Russia",
            "winnerPickImg" : "images/flags/Russia.png",
            "winnerPickKey" : "RUS",
            "loserPickKey" : "BEL",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 31,
            "team1" : "South Korea",
            "team1_key" : "KOR",
            "team2" : "Algeria",
            "team2_key" : "ALG",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Algeria",
            "winnerPickImg" : "images/flags/Algeria.png",
            "winnerPickKey" : "ALG",
            "loserPickKey" : "KOR",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 32,
            "team1" : "Cameroon",
            "team1_key" : "CMR",
            "team2" : "Brazil",
            "team2_key" : "BRA",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Brazil",
            "winnerPickImg" : "images/flags/Brazil.png",
            "winnerPickKey" : "BRA",
            "loserPickKey" : "CMR",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 33,
            "team1" : "Croatia",
            "team1_key" : "CRO",
            "team2" : "Mexico",
            "team2_key" : "MEX",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Mexico",
            "winnerPickImg" : "images/flags/Mexico.png",
            "winnerPickKey" : "MEX",
            "loserPickKey" : "CRO",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 34,
            "team1" : "Australia",
            "team1_key" : "AUS",
            "team2" : "Spain",
            "team2_key" : "ESP",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Spain",
            "winnerPickImg" : "images/flags/Spain.png",
            "winnerPickKey" : "ESP",
            "loserPickKey" : "AUS",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 35,
            "team1" : "Netherlands",
            "team1_key" : "NED",
            "team2" : "Chile",
            "team2_key" : "CHI",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Chile",
            "winnerPickImg" : "images/flags/Chile.png",
            "winnerPickKey" : "CHI",
            "loserPickKey" : "NED",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 36,
            "team1" : "Japan",
            "team1_key" : "JPN",
            "team2" : "Colombia",
            "team2_key" : "COL",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Japan",
            "winnerPickImg" : "images/flags/Japan.png",
            "winnerPickKey" : "JPN",
            "loserPickKey" : "COL",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 37,
            "team1" : "Greece",
            "team1_key" : "GRE",
            "team2" : "Ivory Coast",
            "team2_key" : "CIV",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Ivory Coast",
            "winnerPickImg" : "images/flags/Ivory Coast.png",
            "winnerPickKey" : "CIV",
            "loserPickKey" : "GRE",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 38,
            "team1" : "Italy",
            "team1_key" : "ITA",
            "team2" : "Uruguay",
            "team2_key" : "URU",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Uruguay",
            "winnerPickImg" : "images/flags/Uruguay.png",
            "winnerPickKey" : "URU",
            "loserPickKey" : "ITA",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 39,
            "team1" : "Costa Rica",
            "team1_key" : "CRC",
            "team2" : "England",
            "team2_key" : "ENG",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "England",
            "winnerPickImg" : "images/flags/England.png",
            "winnerPickKey" : "ENG",
            "loserPickKey" : "CRC",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 40,
            "team1" : "Honduras",
            "team1_key" : "HON",
            "team2" : "Switzerland",
            "team2_key" : "SUI",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Switzerland",
            "winnerPickImg" : "images/flags/Switzerland.png",
            "winnerPickKey" : "SUI",
            "loserPickKey" : "HON",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 41,
            "team1" : "Ecuador",
            "team1_key" : "ECU",
            "team2" : "France",
            "team2_key" : "FRA",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "France",
            "winnerPickImg" : "images/flags/France.png",
            "winnerPickKey" : "FRA",
            "loserPickKey" : "ECU",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 42,
            "team1" : "Nigeria",
            "team1_key" : "NGA",
            "team2" : "Argentina",
            "team2_key" : "ARG",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Nigeria",
            "winnerPickImg" : "images/flags/Nigeria.png",
            "winnerPickKey" : "NGA",
            "loserPickKey" : "ARG",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 43,
            "team1" : "Bosnia",
            "team1_key" : "BIH",
            "team2" : "Iran",
            "team2_key" : "IRN",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Iran",
            "winnerPickImg" : "images/flags/Iran.png",
            "winnerPickKey" : "IRN",
            "loserPickKey" : "BIH",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 44,
            "team1" : "USA",
            "team1_key" : "USA",
            "team2" : "Germany",
            "team2_key" : "GER",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Germany",
            "winnerPickImg" : "images/flags/Germany.png",
            "winnerPickKey" : "GER",
            "loserPickKey" : "USA",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 45,
            "team1" : "Portugal",
            "team1_key" : "POR",
            "team2" : "Ghana",
            "team2_key" : "GHA",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Ghana",
            "winnerPickImg" : "images/flags/Ghana.png",
            "winnerPickKey" : "GHA",
            "loserPickKey" : "POR",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 46,
            "team1" : "South Korea",
            "team1_key" : "KOR",
            "team2" : "Belgium",
            "team2_key" : "BEL",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Belgium",
            "winnerPickImg" : "images/flags/Belgium.png",
            "winnerPickKey" : "BEL",
            "loserPickKey" : "KOR",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 47,
            "team1" : "Algeria",
            "team1_key" : "ALG",
            "team2" : "Russia",
            "team2_key" : "RUS",
            "score" : "1-0",
            "tie" : false,
            "winnerPick" : "Russia",
            "winnerPickImg" : "images/flags/Russia.png",
            "winnerPickKey" : "RUS",
            "loserPickKey" : "ALG",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : true,
            "displayInputScore" : true
        }, 
        {
            "id" : 48,
            "team1" : "A1",
            "team2" : "B2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "BRAZIL",
            "winnerPickImg" : "images/flags/BRAZIL.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 49,
            "team1" : "C1",
            "team2" : "D2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "COLOMBIA",
            "winnerPickImg" : "images/flags/COLOMBIA.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 50,
            "team1" : "B1",
            "team2" : "A2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "MEXICO",
            "winnerPickImg" : "images/flags/MEXICO.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 51,
            "team1" : "D1",
            "team2" : "C2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "IVORY COAST",
            "winnerPickImg" : "images/flags/IVORY COAST.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 52,
            "team1" : "E1",
            "team2" : "F2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "SWITZERLAND",
            "winnerPickImg" : "images/flags/SWITZERLAND.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 53,
            "team1" : "G1",
            "team2" : "H2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "GHANA",
            "winnerPickImg" : "images/flags/GHANA.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 54,
            "team1" : "F1",
            "team2" : "E2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "ARGENTINA",
            "winnerPickImg" : "images/flags/ARGENTINA.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 55,
            "team1" : "H1",
            "team2" : "G2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "PORTUGAL",
            "winnerPickImg" : "images/flags/PORTUGAL.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 56,
            "team1" : "A1 B2",
            "team2" : "C1 D2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "BRAZIL",
            "winnerPickImg" : "images/flags/BRAZIL.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 57,
            "team1" : "E1 F2",
            "team2" : "G1 H2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "GHANA",
            "winnerPickImg" : "images/flags/GHANA.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 58,
            "team1" : "B1 A2",
            "team2" : "D1 C2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "IVORY COAST",
            "winnerPickImg" : "images/flags/IVORY COAST.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 59,
            "team1" : "F1 E2",
            "team2" : "H1 G2",
            "score" : "",
            "tie" : false,
            "winnerPick" : "ARGENTINA",
            "winnerPickImg" : "images/flags/ARGENTINA.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 60,
            "team1" : "",
            "team2" : "",
            "score" : "",
            "tie" : false,
            "winnerPick" : "BRAZIL",
            "winnerPickImg" : "images/flags/BRAZIL.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 61,
            "team1" : "",
            "team2" : "",
            "score" : "",
            "tie" : false,
            "winnerPick" : "ARGENTINA",
            "winnerPickImg" : "images/flags/ARGENTINA.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 62,
            "score" : "",
            "tie" : false,
            "winnerPick" : "",
            "winnerPickImg" : "",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }, 
        {
            "id" : 63,
            "team1" : "",
            "team2" : "",
            "score" : "",
            "tie" : false,
            "winnerPick" : "ARGENTINA",
            "winnerPickImg" : "images/flags/ARGENTINA.png",
            "winnerPickKey" : "",
            "loserPickKey" : "",
            "enterWinError" : false,
            "scoreNotTied" : false,
            "gamePicked" : false,
            "displayInputScore" : false
        }
    ]
}